export const REDUCER_KEY = {
  REACT_APP: 'rahmatsaputra-v1.0',
  KEYCHAIN_SERVICE: 'myKeychain',
  SHARED_PREFERENCES_NAME: 'mySharedPrefs',
  SET_WIDTH_LISTENER: 'SET_WIDTH_LISTENER',
  SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
  SELECTED_CONTACT_DATA: 'SELECTED_CONTACT_DATA',
}